#!/bin/sh
# Regenerate manifest.js from images on disk. Run after adding/removing images.
cd "$(dirname "$0")"
{
  echo "// Auto-generated by build-manifest.sh — maps slug to available images."
  echo "window.IMG = {"
  for f in images/property/*.jpg images/property/*.png images/labels/*.jpg images/labels/*.png images/logos/*.png images/logos/*.jpg images/logos/*.svg; do
    [ -f "$f" ] || continue
    slug=$(basename "$f"); slug=${slug%.*}
    case "$f" in images/property/*) kind=property ;; images/logos/*) kind=logo ;; *) kind=label ;; esac
    echo "$slug|$kind|$f"
  done | awk -F'|' '{ imgs[$1] = imgs[$1] sprintf("%s: \"%s\", ", $2, $3) } END { for (s in imgs) printf "  \"%s\": { %s},\n", s, imgs[s] }'
  echo "};"
} > manifest.js
echo "manifest.js written:"
grep -c '": {' manifest.js
