// One-line taglines for the mobile card view. slug → tagline.
window.TAGLINE = {
  // ───────── Napa Valley ─────────
  "inglenook": "Coppola's 36-year resurrection",
  "charles-krug": "Napa's first winery, 1861",
  "beringer": "Both a red AND white #1 wine",
  "robert-mondavi": "The arch that sold the world Napa",
  "opus-one": "Mondavi meets Rothschild",
  "stags-leap": "Beat the French in '76",
  "chateau-montelena": "Won the 1976 Paris whites",
  "schramsberg": "Candlelit caves, Nixon's peace toast",
  "caymus": "Wine of the Year — twice",
  "far-niente": "Azaleas, caves & vintage race cars",
  "duckhorn": "2017's Wine of the Year Merlot",
  "heitz": "Napa's first single-vineyard Cab",
  "sterling": "Famous valley views by cable car",
  "domaine-carneros": "Champagne château & caviar terrace",
  "joseph-phelps": "Birthplace of Insignia",
  "quintessa": "Biodynamic Rutherford amphitheater",
  "hall": "Chrome bunny leaping over the vines",
  "cade": "LEED-gold Howell Mountain eyrie",
  "cuvaison": "Glass box in Carneros Chardonnay",
  "trinchero": "Built by White Zinfandel",
  "davis-estates": "Backen barn over toy-filled caves",
  "melka-estates": "Napa's star winemaker's own label",
  "progeny": "Glass jewel-box on Mount Veeder",
  "stewart-cellars": "Scottish 'abbey' pouring To Kalon",
  "hourglass": "Rock-and-roll cult Cabernet",
  "dana-estates": "100-point cult, nearly impossible to visit",
  "darioush": "Persian palace of golden columns",
  "clos-du-val": "Won the 1986 Paris rematch",
  "round-pond": "Cabernet and its own olive mill",
  "v-sattui": "Salami, lawns, sold-here-only wine",
  "almacerro": "Cult Howell Mountain hideaway",
  "annulus": "Scientists' cult, Rolland-blended Cab",
  "barnett": "Hand-worked vines on a cliff",
  "beaulieu": "2024's #2 wine, Rutherford's benchmark",
  "burgess": "Howell Mountain roots, regenerative reboot",
  "caterwaul": "A 100-pointer's affordable Cabernet",
  "chimney-rock": "2024's #5 Cabernet, Cape Dutch estate",
  "etude": "Carneros Pinot master's Rutherford Cab",
  "faust": "2024's #4 wine, gothic black Victorian",
  "freemark-abbey": "Both red & white at 1976 Paris",
  "massican": "Napa's cult Italian-style whites",
  "newfound": "Rhône reds from a two-person label",
  "paula-kornell": "The Top 100's only US sparkler",
  "pine-ridge": "2025's #27: a $15 white blend",
  "rutherford-hill": "Merlot aged in mile-long caves",
  "st-supery": "Chanel's estate Sauvignon Blanc",
  "sullivan": "'Heart of the vine' Rutherford Cab",
  "turley": "Old-vine Zinfandel temple",
  "vhr": "98-point Oakville, mailing list only",
  "aubert": "2025's #2 wine, a Chardonnay",
  "del-dotto": "Marble caves, taste from the barrel",
  "palmaz": "18-story cave inside a mountain",
  "eleven-eleven": "Born of an airplane chance meeting",
  "raymond": "Crystal cellar & Theater of Nature",
  "tank-garage": "One-off wines in a 1930s gas station",
  "nickel-nickel": "Single-vineyard Cabs, 1770 barn",
  "frogs-leap": "Organic, dry-farmed, corks say 'Ribbit'",
  "rombauer": "The original buttery Chardonnay",
  "pestoni": "Five Swiss-Italian generations, bocce & Barbera",
  "axr": "Named for the rootstock phylloxera killed",
  "caldwell": "Smuggled French clones, volcanic cave",
  "reverie": "ATV rides to hilltop Cabernet Franc",
  // ───────── Sonoma County ─────────
  "buena-vista": "California's oldest premium winery",
  "gundlach-bundschu": "America's oldest family winery",
  "korbel": "America's wedding-day sparkling",
  "sebastiani": "The stonemason who built Sonoma",
  "ridge-lytton-springs": "2025's #3 wine, old-vine Zin",
  "jordan": "A Bordeaux château, just two wines",
  "kendall-jackson": "America's best-selling Chardonnay",
  "chateau-st-jean": "Sonoma's first Wine of the Year",
  "iron-horse": "Bubbles that toasted the Cold War's end",
  "hanzell": "Oldest Chardonnay vines in America",
  "simi": "Isabelle Simi's 66-year reign",
  "rodney-strong": "A Broadway dancer's round winery",
  "coppola-geyserville": "Pool, cabanas & Godfather relics",
  "ferrari-carano": "10,000 tulips at Villa Fiore",
  "rams-gate": "The gateway winery, Backen-built",
  "macrostie": "Glass hilltop, Chardonnay-first",
  "occidental": "Kistler's second act: coastal Pinot",
  "hamel": "Biodynamic rammed-earth estate",
  "donum": "50+ sculptures among the Pinot vines",
  "williams-selyem": "2025's #4 wine, the original cult Pinot",
  "kistler": "California's storied Chardonnay house",
  "medlock-ames": "Organic ranch with a hidden speakeasy",
  "la-crema-saralee": "Pinot in a 1900s hop barn",
  "aperture": "Camera-lens estate, Devil Proof Malbec",
  "bedrock": "2025's #12, old-vine field blend",
  "carlisle": "Old-vine Zin from 1934 plantings",
  "dehlinger": "A Russian River Pinot benchmark",
  "dry-creek-vineyard": "Dry Creek's first post-Prohibition winery",
  "ferren": "A Marcassin protégé's coastal Pinot",
  "flowers": "Vines above the fog, 2 miles from sea",
  "hartford-family": "Single-vineyard old-vine Zinfandel",
  "merry-edwards": "Pioneering woman's cult Sauvignon Blanc",
  "patz-hall": "Chardonnay specialist, won back by founder",
  "platt": "An HP chief's far-coast Pinot",
  "ramey": "The Professor of Chardonnay",
  "ravenswood": "'No Wimpy Wines' old-vine Zin",
  "wayfarer": "2025's #8, grand-cru-style Pinot"
};
